version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - web

  web:
    build: .
    command: gunicorn gptletapi.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:
