# Generated by Django 4.1.5 on 2023-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_app_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
