# Generated by Django 4.1.5 on 2023-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_app_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
