# Generated by Django 4.1.5 on 2023-11-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_app_user_alter_app_author_alter_app_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=1024)),
                ('link_url', models.URLField(max_length=1024)),
            ],
        ),
    ]
