# Generated by Django 4.1.5 on 2023-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_gptentry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptentry',
            name='md_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gptentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
