# Generated by Django 4.1.5 on 2023-11-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gptentry_created_at_gptentry_downvote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptentry',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='gptentry',
            name='upvote',
        ),
    ]
