# Generated by Django 4.1.5 on 2023-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_vote_entryvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptentry',
            name='link_url',
            field=models.URLField(max_length=1024, unique=True),
        ),
    ]
