# Generated by Django 4.1.5 on 2023-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_gptentry_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptentry',
            name='unique_link_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='gptentry',
            name='link_url',
            field=models.URLField(max_length=1024),
        ),
    ]
