# Generated by Django 4.1.5 on 2023-11-12 14:16

from django.db import migrations


def fill_unique_link_url(apps, schema_editor):
    GPTEntry = apps.get_model('app', 'GPTEntry')
    for entry in GPTEntry.objects.all():
        entry.unique_link_url = entry.link_url[:37]
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_gptentry_unique_link_url_alter_gptentry_link_url'),
    ]

    operations = [
        migrations.RunPython(fill_unique_link_url),
    ]
