# Generated by Django 4.1.5 on 2023-11-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_gptentry_unique_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptentry',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
