# Generated by Django 4.1.5 on 2023-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_gptentry_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptentry',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
