# Generated by Django 4.1.5 on 2023-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_gptentry_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_gpts', to='app.tag'),
        ),
    ]
